### ISSUE TITLE
[BUG] libcudftestutil.so build failure blocks cudf submodule sync CI

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids-jni#1006]
**Describe the bug**
https://github.com/NVIDIA/spark-rapids-jni/pull/1005 PR is blocked by

```
11:25:09  [INFO]      [exec] [100%] Linking CXX shared library libcudftestutil.so
11:25:09  [INFO]      [exec] /opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32S against symbol `_ZTVN7testing8internal17TestEventRepeaterE' can not be used when making a shared object; recompile with -fPIC
11:25:09  [INFO]      [exec] collect2: error: ld returned 1 exit status
11:25:09  [INFO]      [exec] gmake[2]: *** [CMakeFiles/cudftestutil.dir/build.make:187: libcudftestutil.so] Error 1
11:25:09  [INFO]      [exec] gmake[1]: *** [CMakeFiles/Makefile2:791: CMakeFiles/cudftestutil.dir/all] Error 2
11:25:09  [INFO]      [exec] gmake: *** [Makefile:156: all] Error 2
```

**Comment by ttnghia** [comment]
Should that be due to https://github.com/rapidsai/cudf/pull/12089?

**Comment by hyperbolic2346** [comment]
I originally thought so, but we don't have that commit yet.

**Comment by robertmaynard** [comment]
Since the error logs contain `libcudftestutil.so` it does indicate that https://github.com/rapidsai/cudf/pull/12089 is part of the build.

**Comment by pxLi** [comment]
> I originally thought so, but we don't have that commit yet.

this error is reported by submodule sync up job, it failed the build so the PR has not been merged yet https://github.com/NVIDIA/spark-rapids-jni/pull/1005

**Comment by sameerz** [comment]
Fixed by https://github.com/rapidsai/cudf/pull/12957
