### ISSUE TITLE
[BUG] submodule sync job can succeed when nightly build will fail

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#1010]
Currently the submodule sync job is regularly passing while the nightly build is regularly failing. This should not be the case, as one of the main points of the submodule sync job is to not move to a new cudf version if that will break the build.  That means somehow the submodule sync job is building in a different way than the nightly build, and that should be fixed.

**Comment by jlowe** [comment]
I think this is related to the nightly build using -DBUILD_TESTS=ON but submodule sync does not.

**Comment by pxLi** [comment]
Previously, we put -DBUILD_TESTS=OFF in submodule sync is for cases that 
if cudf compiling and JNI test passed, we should be fine to update submodule ref.
nightly run could skip -DBUILD_TESTS if needed. 
like pre-merge and nightly could have some diff coverages, but this looks like make people confused.

I will update them to the same.
