### ISSUE TITLE
[BUG] Reconcile differences from CUDF's `row_conversion.cu`

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids-jni#1149]
CUDF JNI has a copy of `row_conversion.cu` that has a couple of material differences from the version in `spark-rapids-jni`. (The changes have to do with which stream is used when constructing a `LIST` column, the use of `cudaMemcpyDefault`, etc.)

It would be good to review those differences, and reconcile them before `row_conversion.cu` is removed from CUDF JNI.

**Comment by ttnghia** [comment]
Code of `row_conversion` was moved into libcudf in https://github.com/rapidsai/cudf/pull/14664, and the version in cudf's JNI was removed. From now, there is just one version of `row_conversion` so close this.
