### ISSUE TITLE
[FEA] Extend the Scalar API with functionality to allow access to native handles.

### ISSUE THREAD

**Issue by nvdbaranec** [NVIDIA/spark-rapids-jni#1307]
This PR https://github.com/NVIDIA/spark-rapids-jni/pull/1303 had to do use a package trampoline to get around lack of access to `Scalar.getScalarHandle()` (access to the native `cudf::list_scalar*`) and the Scalar constructor that takes a native handle.  These would be useful to have in general `Scalar(DType type, long scalarHandle)`

**Comment by mattahrens** [comment]
Need to file corresponding cudf issue.
