### ISSUE TITLE
Check all the JNI unit tests to see if they should be excluded to run with Compute Sanitizer.

### ISSUE THREAD

**Issue by firestarman** [NVIDIA/spark-rapids-jni#1336]
This is a follow-up for PR https://github.com/NVIDIA/spark-rapids-jni/pull/1321.

I do not have enough time to go through all the JNI unit tests one by one, so besides the necessary exclusions to run with Compute Sanitizer successfully in PR https://github.com/rapidsai/cudf/pull/13872, we still need to take a look at other tests to exclude the ones being not suitable to run with Comput Sanitizer by tagging with `@Tag("noSanitizer")`.

**Comment by mattahrens** [comment]
@firestarman -- what work is remaining for this?

**Comment by firestarman** [comment]
Some unit tests may run successfully with Sanitizer, but running with Sanitizer may not be a must. e.g. tests like `[UnsafeMemoryAccessorTest](https://github.com/rapidsai/cudf/blob/20c3aaba97d69bccd0e0bac90d57ec722437bd9b/java/src/test/java/ai/rapids/cudf/UnsafeMemoryAccessorTest.java)` is only for host memory. It is safe to remove the sanitizer check.
I suggest to audit the unit tests to see if each is neccessary to run with Sanitizer. Since PR https://github.com/rapidsai/cudf/pull/13872 does not cover all the tests, only the ones failed the build after enabling Sanitizer.

**Comment by jlowe** [comment]
Is this work really necessary?  I wasn't a fan of running the compute sanitizer on the entire build process, but I don't see much harm running it when there's a short test that happens to not do anything interesting with the GPU.  IMO the cost of digging through the test looking for this and classifying it is not worth the benefit.

**Comment by firestarman** [comment]
OK, close this according to the comment above.
