### ISSUE TITLE
[BUILD] Build JNI and cuDF on cuda 12.2 (Driver R535) for cuda12 classifier

### ISSUE THREAD

**Issue by GaryShen2008** [NVIDIA/spark-rapids-jni#1484]
Build JNI and cuDF on cuda 12.2 (Driver R535) for cuda12 classifier

Right now, we build on cuda 12.0.1.

The requirement is from https://github.com/NVIDIA/spark-rapids/issues/9370.

**Comment by pxLi** [comment]
the change has been applied internally. All work fine now for 23.12
