### ISSUE TITLE
[BUG] Investigate `inclusive_scan` issue in column-row conversion code

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids-jni#1579]
In https://github.com/NVIDIA/spark-rapids-jni/issues/1567, we have the issue with invalid memory access:
```
C++ exception with description "inclusive_scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered" thrown in the test body.
```

https://github.com/NVIDIA/spark-rapids-jni/pull/1577 is a temporary fix, but that does not fix the root cause of the problem and we should spend more time investigating what is really wrong here.

**Comment by sameerz** [comment]
We are not calling the code referenced in #1577 so I am moving this to 24.02 for investigation.

**Comment by ttnghia** [comment]
After investigation, we found that the issue is due to kernel visibility problem. It has been fixed by https://github.com/rapidsai/rapids-cmake/pull/523 and https://github.com/NVIDIA/cuCollections/pull/422.

Close this as resolved.
