### ISSUE TITLE
[FEA] New kernel to support parsing dates/timestamps string with a timezone parameter.

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids-jni#1655]
**Is your feature request related to a problem? Please describe.**
`ToUnixTimestamp` and `GetTimestamp` or more operators require a format parameter, and they are time zone aware operators. Refer to Spark [link](https://github.com/apache/spark/blob/v3.5.0/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/datetimeExpressions.scala#L1269-L1281)

```
val formatter = formatterOption.getOrElse(getFormatter(fmt.toString))
formatter.parse()
```

I think our [GPU implemetation](https://github.com/NVIDIA/spark-rapids/blob/v23.10.0/sql-plugin/src/main/scala/org/apache/spark/sql/rapids/datetimeExpressions.scala#L675) currently does not support non-utc TZ:
```
def parseStringAsTimestamp(
```

When TZ is `Asia/Shanghai`, `to_timestamp("1970-01-01 00:00:00", "yyyy-MM-dd HH:mm:ss")` get negative 8 hours instead of zero.

**Describe the solution you'd like**
Expose the `timeparts` structure, refer to the following code.
Then rebase local time in a time zone to UTC time. Alfred is woring on this.

https://github.com/rapidsai/cudf/blob/v24.02.00a/cpp/src/strings/convert/convert_datetime.cu#L399-L401

```
    auto const timeparts = parse_into_parts(d_str);

    return T{T::duration(timestamp_from_parts(timeparts))};

```

- We can update cudf code.
- We can copy cudf code.  I prefer this option.
We have limited [supported format](https://github.com/NVIDIA/spark-rapids/blob/branch-24.02/docs/compatibility.md#corrected-and-exception-timeparserpolicy)
```
yyyy-MM-dd
yyyy/MM/dd
yyyy-MM
yyyy/MM
dd/MM/yyyy
yyyy-MM-dd HH:mm:ss
MM-dd
MM/dd
dd-MM
dd/MM
MM/yyyy
MM-yyyy
MM/dd/yyyy
MM-dd-yyyy
MMyyyy
```
We can add more supported format in the future.
- Or we can put the code into this PR: https://github.com/NVIDIA/spark-rapids-jni/pull/1539

- [ ] legacy format: [link](https://github.com/apache/spark/blob/v3.5.0/sql/api/src/main/scala/org/apache/spark/sql/catalyst/util/TimestampFormatter.scala#L456-L460)  java.text.SimpleDateFormat
- [ ] new format: java.time.format.DateTimeFormatter
- [ ] When `spark.sql.legacy.timeParserPolicy` is  EXCEPTION,  refer to [link]( https://github.com/apache/spark/blob/v3.5.0/sql/api/src/main/scala/org/apache/spark/sql/catalyst/util/TimestampFormatter.scala#L194)

**Comment by res-life** [comment]
As Haoyang said, we can handle this issue together: https://github.com/NVIDIA/spark-rapids/issues/10032

**Comment by res-life** [comment]
Update: 
After sync-up with @NVnavkumar.
Maybe we have a simple solution via GpuTimeZoneDB directly.
We first get the microseconds from 1970-01-01 00:00:00 in UTC which are called instants.
Then use GpuTimeZoneDB to rebase the microseconds according to the timezone.

For example: Parse("1970-01-01 00:00:00", 'yyyy-MM-dd HH:mm:ss') when session time zone is Aisa/Shanghai.
- First get the microseconds, here it's 0. This means get microseconds from "1970-01-01 00:00:00" in UTC TZ.
- Then use GpuTimeZoneDB.fromUTC(cv, tz) or GpuTimeZoneDB.toUTC(cv, tz) to rebase the microseconds to what we want.

I think https://github.com/NVIDIA/spark-rapids/pull/10100 will close this, only need to double check.
@thirtiseven If above works, then we only need to handle: https://github.com/NVIDIA/spark-rapids/issues/10032

**Comment by thirtiseven** [comment]
The simple solution works, close it and let 10032 track the other parts.
