### ISSUE TITLE
[FEA] Publish the spark-rapids-jni artifact

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#166]
In order for the RAPIDS Accelerator to start depending on the spark-rapids-jni artifact instead of cudf, we need to publish it so it can be downloaded during the RAPIDS Accelerator builds.  Nightly builds should be setup to publish the spark-rapids-jni snapshot jar as we have done for cudf.

**Comment by pxLi** [comment]
We currently deploy only to internal artifactory repo, will add deployment to sonatype oss repo

**Comment by pxLi** [comment]
For nightly snapshots, people should be able to access at 
https://oss.sonatype.org/content/repositories/snapshots/com/nvidia/rapids-4-spark-jni/22.06.0-SNAPSHOT/

We will have a release pipeline for maven central https://github.com/NVIDIA/spark-rapids-jni/issues/16

**Comment by pxLi** [comment]
close via #172
