### ISSUE TITLE
[BUG] The build can be broken due to dependency changes of cudf

### ISSUE THREAD

**Issue by hyperbolic2346** [NVIDIA/spark-rapids-jni#1666]
**Describe the bug**
The cudf build always grabs the [latest RMM](https://github.com/rapidsai/rapids-cmake/blob/c9a3eeb4b291806b9aa940ed7e3ff4a5a30fe907/rapids-cmake/cpm/versions.json#L86) of a specific branch to build. This can and has caused build breakages as the RMM may not be compatible with the cudf version. Most recently, this was the CCCL 2.2 change that hit RMM and cudf at the same time. We pin a specific cudf commit, so our cudf didn't move forward, but RMM was pulled from latest and so it was using CCCL 2.2. This resulted in builds failing even though we had a pinned cudf commit.

**Steps/Code to reproduce bug**
Sync to a commit of spark-rapids-jni before the CCCL 2.2 changes were merged and build.

**Expected behavior**
We run CI and put a specific cudf commit into the submodule to prevent breakages like this. We should be able to continue using the toolchain from the time of the CI build.

**Additional context**
Bradley proposed a fix by creating a `versions.json` file that can be used with [rapids cpm package override](https://docs.rapids.ai/api/rapids-cmake/stable/command/rapids_cpm_package_override/) to pin to the versions that we actually used to build and test in CI. This leaves cmake itself as the only wildcard. This [can also be pinned](https://github.com/rapidsai/rapids-cmake/blob/branch-24.02/README.md#overriding-rapidscmake) to a specific git SHA.

**Comment by sameerz** [comment]
Related issue: https://github.com/rapidsai/cudf/issues/11533

**Comment by bdice** [comment]
A few weeks ago, we had issues with CCCL and I [attempted some build changes](https://github.com/NVIDIA/spark-rapids-jni/compare/7d12f40e6c7787505416148b62bc58b1f4297168...bdice:spark-rapids-jni:cccl-test-latest) that would allow spark-rapids-jni to override rapids-cmake and use CCCL 2.3. The idea is that spark-rapids-jni would be able to inject its own `versions.json` overrides into the pinned cudf submodule, therefore allowing rapids-cmake dependencies to be pinned for libcudf and also spark-rapids-jni. It does not actually build as I had hoped, but I wanted to post this commit's link for posterity in case we can pull something from this as a starting point for the plan @robertmaynard has proposed. This is the most relevant commit from the failed attempt linked above: https://github.com/NVIDIA/spark-rapids-jni/commit/54349cd315d66fa68d2d27a0c8ed4f552a6e4735

**Comment by jlowe** [comment]
@robertmaynard has implemented changes to allow pinning of RAPIDS dependencies.  He also implemented a prototype of how this could work in practice for spark-rapids-jni for a regular build as well as how we would update it as we update the cudf version in the periodic submodule sync builds. Thanks, @robertmaynard! 
See https://github.com/robertmaynard/spark-rapids-jni/commit/85f5a2901afe8ae28c945b9d4e58033edef0c85d for details.

**Comment by GaryShen2008** [comment]
The change depends on a fetch_rapids.cmake file in cuDF repo. But it doesn't exist in branch-24.04 now.
It only exists on the code with a release tag. I suppose it may be created by cuDF DevOps when doing the release build.
I'm checking with Robert Maynard to see if there's an option.

**Comment by bdice** [comment]
The rapids-cmake feature for generating pinned versions is in review here, and should be merged soon: https://github.com/rapidsai/rapids-cmake/pull/530
