### ISSUE TITLE
Output size assertions in unify_json_strings

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#1707]
`unify_json_strings` in map_utils.cu has two places where it asserts on string column data sizes.  The first is this one:
```
  auto const output_size =
    2l +                                            // two extra bracket characters '[' and ']'
    static_cast<int64_t>(chars_size) +
    static_cast<int64_t>(input.size() - 1) +        // append `,` character between input rows
    static_cast<int64_t>(input.null_count()) * 2l;  // replace null with "{}"
  CUDF_EXPECTS(output_size <= static_cast<int64_t>(std::numeric_limits<cudf::size_type>::max()),
               "The input json column is too large and causes overflow.");
```

Eventually cudf will support string columns with more than 2GB of character data, and this assert will fire when we do not want it to.

Later there's a sanity check assertion that used to be super cheap, because before the recent cudf strings column change, calculating the size of character data in a string column involved only accessing data already on the CPU.  Now this assert requires an extra stream synchronization that could be avoided by simply computing it directly from the known `output_size`.
```
  auto const joined_input_size_bytes = joined_input_scv.chars_size(stream);
  CUDF_EXPECTS(joined_input_size_bytes + 2 == output_size, "Incorrect output size computation.");
```
We could consider removing this assertion if we never see issues with `join_strings` doing what it's supposed to do, and that would remove a stream synchronization required to access the string column's character data size.

**Comment by sameerz** [comment]
Keeping this in the backlog until libcudf has long strings support per https://github.com/rapidsai/cudf/issues/13733
