### ISSUE TITLE
[FEA] Mark all kernels with hidden visibility

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids-jni#1734]
To avoid potential issues when using a static cuda runtime in the library, we need to hide all kernels from the external world. This can be done by using the static keyword or hidden visibility adding to the kernel declaration, similar to what has been done in cudf: https://github.com/rapidsai/cudf/pull/14726.

For example, we can use this macro instead of `__global__`:
```
#ifndef JNI_KERNEL
# define JNI_KERNEL __attribute__ ((visibility ("hidden"))) __global__
#endif
```

**Comment by mattahrens** [comment]
Additional documentation needed to show how to do this properly with UDFs.

**Comment by jlowe** [comment]
> Additional documentation needed to show how to do this properly with UDFs.

Filed https://github.com/NVIDIA/spark-rapids-examples/issues/356 to track updating the native UDF examples in the spark-rapids-examples repository.

**Comment by jihoonson** [comment]
I'm working on this issue.
