### ISSUE TITLE
[FEA] [follow-up] getJsonObject: Refine doc comments for new version of getJsonObject

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids-jni#1905]
This is from: https://github.com/NVIDIA/spark-rapids-jni/pull/1893

Due to limited time, #1893 only focus on the correctness of new version of getJsonObject,
use this follow-up issue to refine comments

**Comment by ttnghia** [comment]
Close this as the implementation was changed significantly with more documentation added.
