### ISSUE TITLE
[BUG] Hash was removed from cudf, but it is still referenced in `spark-rapids-jni` tests

### ISSUE THREAD

**Issue by hyperbolic2346** [NVIDIA/spark-rapids-jni#1926]
**Describe the bug**
cuDF removed the hash function with [this PR](https://github.com/rapidsai/cudf/pull/15375). The hash tests in [hash.cpp](https://github.com/NVIDIA/spark-rapids-jni/blob/fa7c2020ae5c8012ae1a520359c5095a4465108f/src/main/cpp/tests/hash.cpp#L61) reference this function and are causing compilation errors if compiled against the latest cudf.

**Comment by gerashegalov** [comment]
fixed by #1929
