### ISSUE TITLE
Support for arm64 in build scripts

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#1958]
The scripts under build/ do not work for ARM builds.  There is a Dockerfile.multi which appears to be unreferenced (at least in this repo) that has some support for ARM, and it's unclear why that file is separate from Dockerfile if it supports building images across multiple architectures.  Ideally build/build-in-docker and build/run-in-docker would work on both x64 and arm64 machines.

**Comment by NvTimLiu** [comment]
I'll take care to this issue later.

**Comment by NvTimLiu** [comment]
Fixed by https://github.com/NVIDIA/spark-rapids-jni/pull/2010
