### ISSUE TITLE
Add formatting tools and enforcement of C++ style

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#202]
It would be nice to have tools to format and precommit checks to enforce a C++ style as was done in the RAPIDS cudf repository with clang-format.

**Comment by ttnghia** [comment]
Please priority this.

In addition, I prefer to use the existing libcudf C++ `.clang-format` style as it is pretty complete. The clang-format style from cudf JNI is not that nice.

**Comment by jlowe** [comment]
Any idea why cudf JNI and libcudf C++ are using different formats?

**Comment by ttnghia** [comment]
I traced back git history and found that JNI `.clang-format` was created on 6/13/2019 by @revans2 while libcudf `.clang-format` was added later on 10/30/2019.

**Comment by ttnghia** [comment]
@jlowe Should this be closed by https://github.com/NVIDIA/spark-rapids-jni/pull/1244?

**Comment by jlowe** [comment]
Almost.  The formatting tools are there, but arguably we should have formatting enforcement in CI otherwise we'll keep reviewing what should be small PRs but become huge because some people are formatting and others are not.

**Comment by ttnghia** [comment]
@pxLi for visibility: we need to setup CI style check.

**Comment by pxLi** [comment]
> @pxLi for visibility: we need to setup CI style check.

sounds good to me. Please help provide some minimum steps of how the formating tool should work in CI, thanks

We will try setup CI for it 👍

**Comment by ttnghia** [comment]
Maybe this: https://github.com/NVIDIA/spark-rapids-jni/pull/1244#issuecomment-1615130821.

**Comment by pxLi** [comment]
> Maybe this helps on how to do it: [#1244 (comment)](https://github.com/NVIDIA/spark-rapids-jni/pull/1244#issuecomment-1615130821).
> 

their script seems too much for our usage. We can just run pre-commit as added in https://github.com/NVIDIA/spark-rapids-jni/pull/1244/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R6

> Before CI style check can be enforced, we must have PR to reformat all the code.

sure, cc @yinqingh to help with this ticket. 

We will need an extra github action to help check clang format before merging.

**Comment by pxLi** [comment]
closing by #1597. Feel free to reopen if require some follow-up
