### ISSUE TITLE
[FEA][Performance] Merge multiple "copy_if_else" for "case when" in the case of multiple branches

### ISSUE THREAD

**Issue by winningsix** [NVIDIA/spark-rapids-jni#2084]
**Is your feature request related to a problem? Please describe.**
`copy_if_else` is an expensive operation (shown in below nsys trace) and it happens in the case of "case when". And there exists some opportunities we could avoid multiple `copy_if_else` and consolidate them into a single one. 
![image](https://github.com/NVIDIA/spark-rapids-jni/assets/2278268/edeed5fa-c625-4677-a0e6-87a923376332)

**Describe the solution you'd like**
Consolidating multiple `copy_if_else` into a single one in case when without side effect case.

**Comment by res-life** [comment]
JNI PR: https://github.com/NVIDIA/spark-rapids-jni/pull/2079
