### ISSUE TITLE
Improved detection of bad dependencies from native build

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#2164]
**Is your feature request related to a problem? Please describe.**
#2162 should be something caught during the build process.

**Describe the solution you'd like**
The build should analyze the dynamic dependencies of the shared libraries being produced and verify nothing unexpected appears as a dependency.

**Comment by mattahrens** [comment]
Scope: add new test in a different environment such that NVIDIA driver is the only NVIDIA package available.

**Comment by pxLi** [comment]
Let me try figure out some good solutions to detect the issue during submodule-syncup, pre-merge or nightly-build

**Comment by gerashegalov** [comment]
Different environment could be just another Dockerfile (different from the one used for build-in-docker) for testing that does not contain (nor mounts from the host) the paths containing cudart.

**Comment by pxLi** [comment]
> Different environment could be just another Dockerfile (different from the one used for build-in-docker) for testing that does not contain (nor mounts from the host) the paths containing cudart.

yep, this could simply be within a non-cuda image, and then check ldd status
