### ISSUE TITLE
[BUG] submodule sync failing with CMake error `BS::thread_pool not found`

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/spark-rapids-jni#2260]
The submodule sync pipeline currently fails with this error:
```
13:21:42  [INFO]      [exec] CMake Error at /home/jenkins/agent/workspace/jenkins-spark-rapids-jni_submodule-sync-dev-3479/target/libcudf/cmake-build/_deps/kvikio-build/kvikio-targets.cmake:56 (set_target_properties):
13:21:42  [INFO]      [exec]   The link interface of target "kvikio::kvikio" contains:
13:21:42  [INFO]      [exec] 
13:21:42  [INFO]      [exec]     BS::thread_pool
13:21:42  [INFO]      [exec] 
13:21:42  [INFO]      [exec]   but the target was not found. 
```

**Comment by ttnghia** [comment]
CC @jlowe: the previous issue was fixed, this is a new one.

**Comment by jlowe** [comment]
Yes, was just fixed by rapidsai/cudf#16398.  Just kicked off a submodule sync build, will close this if it passes as expected.

**Comment by ttnghia** [comment]
I've been staring at that build. It failed with the issue here.

**Comment by ttnghia** [comment]
Suspect that it is due to https://github.com/rapidsai/cudf/pull/16210.

**Comment by jlowe** [comment]
> I've been staring at that build for 30 minutes.

That's not the build I kicked off.  The build that failed did not include rapidsai/cudf#16210 which was committed just as you filed this issue.

**Comment by jlowe** [comment]
Submodule sync build is now passing.
