### ISSUE TITLE
[FEA] Move to RMM apis get_current_device_resource_ref

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids-jni#2358]
In the spark-rapids-jni code I see several calls to `get_current_device_resource`, but this is going to be deprecated by https://github.com/rapidsai/rmm/pull/1661. We need to move to `get_current_device_resource_ref`.

Corresponding cuDF issue: https://github.com/rapidsai/cudf/issues/16673

**Comment by harrism** [comment]
To be clear, #1661 does not deprecate anything yet, and is still experimental.
