### ISSUE TITLE
[BUG] submodule sync script assumes cudf commits are required to see any changes

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#2484]
The cudf submodule sync script has [this logic](https://github.com/NVIDIA/spark-rapids-jni/blob/branch-24.12/ci/submodule-sync.sh#L61-L64):
```bash
if [[ "${cudf_sha}" == "${cudf_prev_sha}" ]]; then
  echo "Submodule is up to date."
  exit 0
fi
```
The problem with this logic is that there could be changes to cudf dependencies _without_ changes to cudf itself, and the only way to pick up those changes is to run the submodule sync.  That will build with `-Dlibcudf.dependency.mode=latest` causing any new versions of cudf dependencies to be picked up in the pinned versions file.

**Comment by pxLi** [comment]
Eliminating the check that skips certain runs and executing the build every time, or comparing the latest commits across all RAPIDS ecosystem projects, might help resolve the issue. 

Currently, with the patch framework, each submodule-sync run takes approximately 2.5 hours. The check was initially added to conserve resources. Do you have any suggestions for this? thank you
