### ISSUE TITLE
[FEA] Introduce kudo shuffle format.

### ISSUE THREAD

**Issue by liurenjie1024** [NVIDIA/spark-rapids-jni#2496]
## Design

 Kudo serialization format is optimized for columnar batch serialization used during spark shuffle, which significantly improved serialization/deserialization time compared to jcudf  serialization format. The improvements are based on two observations:

1. During spark shuffle we have a lot of contexts provided by runtime such as table schema, that means we could simplify headers. In kudo's header, we only contains necessary fields such as offset, number of rows, data lens, and one byte for each column to indicate whether it has validity buffer.
2. Gpu's columnar batch is typically much larger than cpu's vectorized execution engine, that means we almost always need to do batch concatanation in shuffle read time. When serializing a part of a larger columnar batch, unlike jcudf, which calculates exact validity buffer and offset buffer, we only record offset and number of rows in header, and copy necessay bytes, since the exact buffer could be restored at read time when do concating. This saves a lot of compuation when doing serialization.

## Performance

We have observed 30%-4000% serialization time improvement, up to 200% deserialization time improvement, and similar concat batching performance.

**Comment by jlowe** [comment]
@liurenjie1024 please add details to this.  As-is, it's just a headline with nothing else to go on.
