### ISSUE TITLE
[BUG] Incremental builds do not work with patching framework

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#2498]
After #2497 incremental builds do not work properly.  Trying to build the `package` target after the first time will fail because cudf source has already been patched.  Specifying `-Dsubmodule.patch.skip` will get past this, but it will also skip building any of the C++ code, i.e.: anything under thirdparty/cudf/cpp/, thirdparty/java/src/main/native/, or src/main/cpp/.  That means you end up running with old code which is quite confusing.

A workaround is to always build the `clean package` targets rather than just `package`, but that's significantly slower due to all the C++ dependencies being downloaded from scratch each time.

**Comment by sameerz** [comment]
Fixed by https://github.com/NVIDIA/spark-rapids-jni/pull/2502
