### ISSUE TITLE
[BUG] CI does not catch missing copyright or license on new files

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#2571]
One of the CI runs on #2559 should have failed due to a missing copyright and license header on a source file but it did not.  We should use something like apache-rat-plugin to catch this error of omission in CI.

**Comment by mattahrens** [comment]
@pxLi can this be addressed with the common build repo?

**Comment by pxLi** [comment]
> [@pxLi](https://github.com/pxLi) can this be addressed with the common build repo?

Yes, this could be a good shared action usage to verify the license header change.

I will create another ticket in common repo
