### ISSUE TITLE
[BUG] license header failed "fatal: bad object"

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids-jni#2614]
**Describe the bug**
e.g. 
https://github.com/NVIDIA/spark-rapids-jni/actions/runs/11930468653/job/33251309894 fail for submodule-sync change https://github.com/NVIDIA/spark-rapids-jni/pull/2611/files

https://github.com/NVIDIA/spark-rapids-jni/actions/runs/11944100102/job/33294422624

```
fatal: bad object 65f74552d2fea9be7b2b1d24a9e82dfbfdefc852
```
it's unclear what has failed the check like git history or submodule updates

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**

**Environment details (please complete the following information)**
 - Environment location: [Standalone, YARN, Kubernetes, Cloud(specify cloud provider)]
 - Spark configuration settings related to the issue

**Additional context**

**Comment by pxLi** [comment]
this might be the feature branch is merged too fast to break the git diff check, please help consider how can we avoid this situation, thanks @YanxuanLiu (like skip action if special fea-branch)

**Comment by pxLi** [comment]
also see occurence in normal commit change https://github.com/NVIDIA/spark-rapids-jni/actions/runs/11946023357/job/33299691974

**Comment by YanxuanLiu** [comment]
> Another issue: [#2610](https://github.com/NVIDIA/spark-rapids-jni/pull/2610)

partly fixed the issue, please upmerge and trigger again, thanks!
