### ISSUE TITLE
[FEA] replace spdlog usage with new rapids logger

### ISSUE THREAD

**Issue by abellina** [NVIDIA/spark-rapids-jni#2695]
This task https://github.com/rapidsai/build-planning/issues/104 documents removing spdlog in favor of a logger API that will become the standard among cuDF/RMM/and any other library.

We should try to use this directly, instead of using spdlog directly. We'll need to make sure we can retain the functionality we need for our state machine logging so we should be following the development of the new logger api to ensure it satisfies our needs as well.

Related https://github.com/NVIDIA/spark-rapids-jni/pull/2679

**Comment by jlowe** [comment]
I don't think we want to tie our logging to the cudf logger.  Currently we try to disable cudf logging, and if we use their logger then we'll also disable our own logging.  Therefore we'll need to keep the loggers separate so we can control them separately.
