### ISSUE TITLE
[FEA] Better way to build/run cudf native tests

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids-jni#980]
**Is your feature request related to a problem? Please describe.**
A lot of developers don't build/run in CUDF directly any more. It is all done through spark-rapids-jni.  This becomes a problem when we find a bug in CUDF and try to create a C++ test to reproduce the error.  It would really be great if there were a simple way to build/run the c++ tests in thirdparty/cudf in addition to the C++ tests that we can run from spark-rapids-jni. I don't think we need to do this by default. But it would make developing these tests a lot simpler.

**Comment by jlowe** [comment]
This should be relatively straightforward.  We're hardcoding  BUILD_TESTS=OFF in build-libcudf.xml, and it's straightforward to make this a parameterized setting based on a Maven property passed down to the Ant execution.  If the existing `install` target just builds the tests and doesn't run them, then we would need to add a step to run the tests (which could be a separate, conditional antrun execution in the main pom).

**Comment by jlowe** [comment]
Since #2115 it's easy to build libcudf tests and benchmarks from a spark-rapids-jni build by specifying -DBUILD_CUDF_TESTS=ON and -DBUILD_CUDF_BENCHMARKS=ON, respectively.
