### ISSUE TITLE
[FEA] Add CI for nightly or weekly fuzz testing for SparkRMM retry

### ISSUE THREAD

**Issue by revans2** [NVIDIA/spark-rapids-jni#981]
**Is your feature request related to a problem? Please describe.**
I added in a fuzz tester for Spark RMM retry

https://github.com/NVIDIA/spark-rapids-jni/pull/977

It would be nice to run it with a random seed nightly or weekly to make sure that things are still working, and possibly find some errors that need to be fixed.

**Comment by GaryShen2008** [comment]
Hi @revans2, besides a random seed, what about the other parameters?
Try to understand what's the test matrix of the parameters we should cover in the nightly CI.

**Comment by revans2** [comment]
I would just run with something like

```
java -cp ./target/\*:/home/roberte/.m2/repository/org/slf4j/slf4j-api/2.0.6/slf4j-api-2.0.6.jar com.nvidia.spark.rapids.jni.RmmSparkMonteCarlo --taskMaxMiB=2048 --gpuMiB=3072 --skewed --allocMode=ASYNC
```

I am working on some fixes for a few things. Stuff like catching unexpected errors and exiting with a proper result code if there were errors or failures. But even then we would want to verify that we didn't hang, so we would want a timeout that is not too high.

**Comment by pxLi** [comment]
Try in understand the minimal requirement, 
the test run just require `JVM runtime + JNI.jar + slf4j-api-2.0.6.jar`, right? thanks

**Comment by revans2** [comment]
@pxLi yes that is what I needed to make it work.

**Comment by pxLi** [comment]
close as CI has been setup.

we may improve the script sometime
